<?php

/**
 * BaseUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sf_guard_user_id
 * @property integer $hcoin
 * @property sfGuardUser $User
 * 
 * @method integer     getId()               Returns the current record's "id" value
 * @method integer     getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method integer     getHcoin()            Returns the current record's "hcoin" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method UserProfile setId()               Sets the current record's "id" value
 * @method UserProfile setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method UserProfile setHcoin()            Sets the current record's "hcoin" value
 * @method UserProfile setUser()             Sets the current record's "User" value
 * 
 * @package    betyolo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_profile');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('hcoin', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}