<?php

/**
 * BaseBetyoloBet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $creator_id
 * @property string $description
 * @property integer $side_a_id
 * @property integer $side_b_id
 * @property integer $category_id
 * @property integer $status
 * @property integer $result
 * @property BetyoloCategory $BetyoloCategory
 * @property BetyoloSide $SideA
 * @property BetyoloSide $SideB
 * 
 * @method integer         getCreatorId()       Returns the current record's "creator_id" value
 * @method string          getDescription()     Returns the current record's "description" value
 * @method integer         getSideAId()         Returns the current record's "side_a_id" value
 * @method integer         getSideBId()         Returns the current record's "side_b_id" value
 * @method integer         getCategoryId()      Returns the current record's "category_id" value
 * @method integer         getStatus()          Returns the current record's "status" value
 * @method integer         getResult()          Returns the current record's "result" value
 * @method BetyoloCategory getBetyoloCategory() Returns the current record's "BetyoloCategory" value
 * @method BetyoloSide     getSideA()           Returns the current record's "SideA" value
 * @method BetyoloSide     getSideB()           Returns the current record's "SideB" value
 * @method BetyoloBet      setCreatorId()       Sets the current record's "creator_id" value
 * @method BetyoloBet      setDescription()     Sets the current record's "description" value
 * @method BetyoloBet      setSideAId()         Sets the current record's "side_a_id" value
 * @method BetyoloBet      setSideBId()         Sets the current record's "side_b_id" value
 * @method BetyoloBet      setCategoryId()      Sets the current record's "category_id" value
 * @method BetyoloBet      setStatus()          Sets the current record's "status" value
 * @method BetyoloBet      setResult()          Sets the current record's "result" value
 * @method BetyoloBet      setBetyoloCategory() Sets the current record's "BetyoloCategory" value
 * @method BetyoloBet      setSideA()           Sets the current record's "SideA" value
 * @method BetyoloBet      setSideB()           Sets the current record's "SideB" value
 * 
 * @package    betyolo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBetyoloBet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('betyolo_bet');
        $this->hasColumn('creator_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('side_a_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('side_b_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('result', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BetyoloCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('BetyoloSide as SideA', array(
             'local' => 'side_a_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('BetyoloSide as SideB', array(
             'local' => 'side_b_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}