<?php

/**
 * BaseBetyoloSide
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $category_id
 * @property BetyoloCategory $BetyoloCategory
 * @property Doctrine_Collection $BetyoloBet
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method integer             getCategoryId()      Returns the current record's "category_id" value
 * @method BetyoloCategory     getBetyoloCategory() Returns the current record's "BetyoloCategory" value
 * @method Doctrine_Collection getBetyoloBet()      Returns the current record's "BetyoloBet" collection
 * @method BetyoloSide         setName()            Sets the current record's "name" value
 * @method BetyoloSide         setDescription()     Sets the current record's "description" value
 * @method BetyoloSide         setCategoryId()      Sets the current record's "category_id" value
 * @method BetyoloSide         setBetyoloCategory() Sets the current record's "BetyoloCategory" value
 * @method BetyoloSide         setBetyoloBet()      Sets the current record's "BetyoloBet" collection
 * 
 * @package    betyolo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBetyoloSide extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('betyolo_side');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BetyoloCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('BetyoloBet', array(
             'local' => 'id',
             'foreign' => 'side_a_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}