<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/10/06 10:06:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=betyolo',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
