<?php

/**
 * BetyoloSideTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BetyoloSideTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BetyoloSideTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BetyoloSide');
    }
}