<?php

/**
 * BetyoloCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BetyoloCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BetyoloCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BetyoloCategory');
    }
}