<?php

/**
 * BetyoloBetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BetyoloBetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BetyoloBetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BetyoloBet');
    }
}