<?php

/**
 * BetyoloBet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betyolo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BetyoloBet extends BaseBetyoloBet
{
  public static $statuses = array(
    1 => "on going",
    2 => "exprie",
  );

  public static $results = array(
    1 => "A win",
    2 => "B win",
    3 => "None",
  );
  
  public function printStatus() 
  {
  	return self::$statuses[$this->getStatus()];
  }

  public function printResult()
  {
  	return self::$results[$this->getResult()];
  }
}
