<?php

/**
 * Transaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betyolo
 * @subpackage model
 * @author     Nguyen Anh Tuan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Transaction extends BaseTransaction
{
  #type
  const DEPOSIT  = 1;
  const WITHDRAW = 2;

  #status
  const PENDING   = 1;
  const COMPLETED = 2;
  const FAILED    = 3;
  static $statuses = array(
    self::PENDING   => 'PENDING',
    self::COMPLETED => 'COMPLETED',
    self::FAILED    => 'FAILED',
  );

  static public $amounts = array(
    10000 => 10000,
    20000 => 20000,
    50000 => 50000,
    100000 => 100000,
    200000 => 200000,
    300000 => 300000,
    400000 => 400000,
    500000 => 500000,
  );

  public function deposit($hcoin = 0)
  {
    if ($this->getStatus() != self::PENDING || $hcoin <= 0 ) {
      return false;
    }

    $user_profile = Doctrine_Core::getTable('sfGuardUser')->find($this->getUserId())->getProfile();

    if (!$user_profile->getHcoin()) {
      $user_profile->setsfGuardUserId($this->getUserId());
      $user_profile->setHcoin($hcoin);
    } else {
      $user_profile->setHcoin($user_profile->getHcoin() + $hcoin);
    }
    $user_profile->save();

    $this->setStatus(self::COMPLETED);
    $this->save();

    return true;
  }

  public function cancelTransaction()
  {
    $this->setStatus(self::FAILED);
    $this->save();
  }

  public function withdraw($hcoin = 0)
  {
    $user_profile = Doctrine_Core::getTable('sfGuardUser')->find($this->getUserId())->getProfile();
    if(!$user_profile) {
      return false;
    }
    $user_hcoin = $user_profile->getHcoin();
    if ($this->getStatus() != self::PENDING || $hcoin <= 0  || $hcoin > $user_hcoin) {
      return false;
    }

    $user_profile->setHcoin($user_hcoin - $hcoin);
    $user_profile->save();

    $this->setStatus(self::COMPLETED);
    $this->save();

    return true;
  }
}
