<?php

/**
 * Transaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betyolo
 * @subpackage model
 * @author     Nguyen Anh Tuan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Transaction extends BaseTransaction
{
	const DEPOSIT  = 1;
	const WITHDRAW = 2;
}
