<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adduserprofile extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user_profile', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'sf_guard_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'hcoin' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('user_profile');
    }
}