<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addbetyolobet extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('betyolo_bet', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'creator_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 4000,
             ),
             'side_a_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'side_b_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'status' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'result' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('betyolo_bet');
    }
}