<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtransaction extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('transaction', array(
            'id' => 
            array(
                'type' => 'integer',
                'length' => 8,
                'autoincrement' => true,
                'primary' => true,
            ),
            'user_id' => 
            array(
                'type' => 'integer',
                'notnull' => true,
                'length' => 8,
            ),
            'type' => 
            array(
                'type' => 'integer',
                'notnull' => true,
                'length' => 8,
            ),
            'amount' => 
            array(
                'type' => 'integer',
                'notnull' => true,
                'length' => 8,
            ),
            'status' => 
            array(
                'type' => 'integer',
                'notnull' => true,
                'length' => 8,
            ),
            'created_at' => 
            array(
                'notnull' => true,
                'type' => 'timestamp',
                'length' => 25,
            ),
            'updated_at' => 
            array(
                'notnull' => true,
                'type' => 'timestamp',
                'length' => 25,
            ),
        ), array(
            'indexes' => 
            array(
            ),
            'primary' => 
            array(
                0 => 'id',
            ),
        ));
    }

    public function down()
    {
        $this->dropTable('transaction');
    }
}
